config/routes.rb
Glitter::Application.routes.draw do

  devise_for :users,:controllers => { :registrations => 'registrations' }
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  match 'auth/:provider/callback' => "identities#create", :via => [:get,:post]
  match 'auth/failure' => "identities#failed_to_authenticate", :via => [:get,:post]
  

  resources :projects
  resources :identities, only: [:destroy,:index]
  resources :comments, only: [:new, :create, :destroy]
  resources :glitterposts
  resources :notifications, only: [:index,:show]

  
  post 'glitterposts/:id/edit' => 'glitterposts#update'
  get '/inspire' => 'projects#index'
  get '/dashboard' => 'dashboard#index', :as => :dashboard
  get '/:username/follow' => 'relationships#follow'
  get '/:username/unfollow' => 'relationships#unfollow'
  get '/:username' => 'users#show'
  get '/:username/projects' => 'projects#user_show'
  get '/:username/projects/following' => 'users#list_followed_projects', :as => :followed_projects
  get '/:username/:project' => 'projects#show'
  get '/:username/:project/commits' => 'projects#commits'
  get '/:username/:project/commit/:tree_id' => 'projects#projectcommit'
  get '/:username/:project/master/:image_name' => 'projects#masterbranch', :image_name => /[^\/]*/
  get '/:username/:project/master/:image_name/history' => 'projects#file_history', :image_name => /[^\/]*/
  get '/:username/:project/createsvg' => 'projects#new_svg'
  get '/:username/:project/newfile' => 'projects#newfile'
  get '/:username/:project/master/:image_name/edit' => 'projects#edit_svg', :image_name => /[^\/]*/
  get '/:username/:project/master/:image_name/update' => 'projects#update', :image_name => /[^\/]*/
  delete '/:username/:project/master/:image_name/delete' => 'projects#file_delete', :image_name => /[^\/]*/
  post '/:username/:project/follow' => 'projects#follow'
  get '/:username/:project/fork' => 'projects#fork'
  get '/:username/:project/forkyou' => 'projects#forkyou'
  get '/:username/:project/pull' => 'projects#pull_request'
  get '/:username/:project/pull/:pull_id' => 'projects#pull'
  get '/:username/:project/pull/:pull_id/merge' => 'projects#merge'
  get '/:username/:project/pull/:pull_id/close' => 'projects#close'
  get '/:username/:project/pull/:pull_id/open' => 'projects#open'
  get '/:username/:project/pulls' => 'projects#pulls'
  get '/:username/:project/settings' => 'projects#settings'
  get '/:username/:project/issues/new' => 'issues#new'
  get '/:username/:project/issues' => 'issues#index'
  post '/:username/:project/issues/new' => 'issues#create'
  get '/:username/:project/issue/:sub_id' => 'issues#show'
  post '/:username/:project/issue/:sub_id/close' => 'issues#close'

  get '/:username/:project/:xid' => 'projects#show'
  get '/:username/:project/:xid/commits' => 'projects#commits'
  get '/:username/:project/:xid/commit/:tree_id' => 'projects#projectcommit'
  get '/:username/:project/:xid/master/:image_name' => 'projects#masterbranch', :image_name => /[^\/]*/
  get '/:username/:project/:xid/master/:image_name/history' => 'projects#file_history', :image_name => /[^\/]*/
  get '/:username/:project/:xid/createsvg' => 'projects#new_svg'
  get '/:username/:project/:xid/newfile' => 'projects#newfile'
  get '/:username/:project/:xid/master/:image_name/edit' => 'projects#edit_svg', :image_name => /[^\/]*/
  get '/:username/:project/:xid/master/:image_name/update' => 'projects#update', :image_name => /[^\/]*/
  delete '/:username/:project/:xid/master/:image_name/delete' => 'projects#file_delete', :image_name => /[^\/]*/
  post '/:username/:project/:xid/follow' => 'projects#follow'
  get '/:username/:project/:xid/fork' => 'projects#fork'
  get '/:username/:project/:xid/forkyou' => 'projects#forkyou'
  get '/:username/:project/:xid/pull' => 'projects#pull_request'
  get '/:username/:project/:xid/pull/:pull_id' => 'projects#pull'
  get '/:username/:project/:xid/pull/:pull_id/merge' => 'projects#merge'
  get '/:username/:project/:xid/pull/:pull_id/close' => 'projects#close'
  get '/:username/:project/:xid/pull/:pull_id/open' => 'projects#open'
  get '/:username/:project/:xid/pulls' => 'projects#pulls'
  get '/:username/:project/:xid/settings' => 'projects#settings'
  get '/:username/:project/:xid/issues' => 'issues#index'
  get '/:username/:project/:xid/issue/:sub_id' => 'issues#show'
  get '/:username/:project/:xid/issues/new' => 'issues#new'
  post '/:username/:project/:xid/issues/new' => 'issues#create'
  post '/:username/:project/:xid/issue/:id/close' => 'issues#close'

  
  resources :projects do
    member do
      get 'projects/:id/invite.xml' => 'projects#invite'
      post :file_upload
      post :file_update
      post :handle_pull_request
      post :create_svg, :as => :create_svg
      post :edit_svg, :as => :edit_svg
      post :update_svg, :as => :update_svg
    end
  end 
end

app/controllers/projects_controller.rb
require 'grit'

class ProjectsController < ApplicationController
  before_filter :store_return_to
  before_filter :authenticate_user!, except: [:show, :commits, :projectcommit, :masterbranch, :file_history, :pulls, :pull]

  def new
    @project = Project.new
    @projects = current_user.projects
  end

  def index
    @projects = Project.where("private IS NOT TRUE AND user_id <> ?", current_user.id)
  end

  def destroy
    @project = Project.find params[:id]
    if current_user.id == @project.user_id
      @project.destroy # There is an after_destroy callback in the Project model that deletes the files.
      flash[:notice] = "It has been destroyed!"
      redirect_to dashboard_path
    else
      flash[:error] = "You don't have permission for this command!"
      redirect_to @project.urlbase
    end
  end

  def create
    project = Project.new project_params
    project.user_id = current_user.id
    if params[:commit]=="Private"
      project.private = true
      project.uniqueurl = SecureRandom.hex
    end
    if project.save
      project.parent = project.id
      project.save
      unless project.private
        notification = Notification.new(:actor => current_user, :action => 4, :object_type => 0, :object_id => project.id)
        notification.victims << current_user.followers
        notification.save!
      end
      redirect_to project.urlbase
    else
      flash[:alert] = "Didn't save project!"
      redirect_to new_project_path
    end
  end

  def follow
    @user = User.find_by username: params[:username]
    @project = Project.find_by user_id: @user.id, name: params[:project]
    unless @user == current_user
      if ProjectFollower.where(:follower => current_user, :followed_project => @project).empty?
        ProjectFollower.create(:follower => current_user, :followed_project => @project)
        Notification.create(
          :actor => current_user,
          :action => 1,
          :object_type => 0,
          :object_id => @project.id,
          :victims => [@project.user]
        )
      end
      flash[:notice] = "You're now following #{@user.username}/#{@project.name}"
    else
      flash[:notice] = "You're the owner of this project, you automatically receive updates."
    end
    redirect_to @project.urlbase
  end

  def show
    @user = User.find_by username: params[:username]
    @project = Project.find_by user_id: @user.id, name: params[:project]
    if Rails.env.production?
      @invite_uri = "sparkleshare://#{ENV['OPENSHIFT_APP_DNS'].downcase}/projects/#{params[:id]}/invite.xml" # If it's in production.
    else
      @invite_uri = "#{Rails.root}/uploads/#{Rails.env}/projects/#{params[:id]}/invite.xml" # If not in production.
    end
    @images = []
    barerepo = @project.barerepo
    unless barerepo.empty?
      headcommit = barerepo.head.target
      headtree = barerepo.lookup(headcommit.tree_id)
      headtree.each do |blob|
        link = File.join(@project.urlbase,'master',blob[:name])
        @images.push({
           :link => link,:name => blob[:name],:url => @project.imageurl(blob[:name])
        })
      end
    end
    @comments = Comment.where(polycomment_type: "project", polycomment_id: @project.id)
    @comments = pg @comments, 10
    @comment = Comment.new
    @ajax = params[:page].nil? || params[:page] == 1
  end

  def user_show
    @user = User.find_by username: params[:username]
    @projects = @user.projects
  end

  def commits
    @user = User.find_by username: params[:username]
    @project = Project.find_by user_id: @user.id, name: params[:project]
    @commits = []
    unless @project.barerepo.empty?
      walker = Rugged::Walker.new(@project.barerepo)
      walker.push(@project.barerepo.head.target)
      walker.each { |c| @commits.push(c) }
    end
    @comments = Comment.where(polycomment_type: "commit", polycomment_id: params[:tree_id])
    @comments = pg @comments, 10
  end

  def projectcommit
    @user = User.find_by username: params[:username]
    @project = Project.find_by user_id: @user.id, name: params[:project]
    @images = []
    barerepo = @project.barerepo
    unless barerepo.empty?
      tree = barerepo.lookup(params[:tree_id])
      tree.each do |blob|
        link = File.join(@project.urlbase,'master',blob[:name])
        data = barerepo.read(blob[:oid]).data
        @images.push({
          :link => link,:data => data,:name => blob[:name]
        })
      end
    end
    @comments = Comment.where(polycomment_type: "commit", polycomment_id: params[:tree_id])
    @comment = Comment.new
    @id = params[:tree_id]
  end

  # Given a filename, view the state of the file in master.
  # Since we aren't doing much branch hopping on the app itself, this
  # is useful for fetching the current state of a file in a project.

  def masterbranch
    @user = User.find_by username: params[:username]
    @project = Project.find_by user_id: @user.id, name: params[:project]
    @imageurl = File.join @project.satellitedir, params[:image_name]
    @comments = Comment.where(polycomment_type: "file", polycomment_id: params[:image_name])
    @comments = @comments.paginate(page: params[:page], per_page: 10)
    @comments = pg @comments, 10
    @comment = Comment.new
    @ajax = params[:page].nil? || params[:page] == 1
  end

  # Given a filename, view it's entire commit history, including author
  # information, etc. Only one file's history may be viewed at a time, so
  # please note that this is different from the project's commit history.

  def file_history
    @user = User.find_by username: params[:username]
    @project = Project.find_by user_id: @user.id, name: params[:project]
    @bloblist = Array.new
    walker = Rugged::Walker.new(@project.barerepo)
    walker.push(@project.barerepo.head.target)
    walker.each do |commit|
      tree = @project.barerepo.lookup(commit.tree_id)
      tree.each do |blob|
        if blob[:name] == params[:image_name]
          blobdata = @project.barerepo.read(blob[:oid]).data
          image = {
            :name => blob[:name],
            :data => blobdata
          }
          @bloblist << [image , commit]
        end
      end
    end
  end

  # Sparkleshare integration.

  def invite
    @user = User.find_by username: params[:username]
    @project = Project.find_by user_id: @user.id, name: params[:project]
    mime_type = Mime::Type.lookup_by_extension('xml')
    content_type = mime_type.to_s unless mime_type.nil?
    @git_dir = "/#{@project.user.email}/#{@project.name}"
    render :layout => false, :content_type => content_type
  end

  # Let's users upload a new file to the project through a
  # different page. Original functionality used to exist in the
  # project show page, moved to a separate page now.

  def newfile
    @user = User.find_by username: params[:username]
    @project = Project.find_by user_id: @user.id, name: params[:project]
  end

  def update
    @user = User.find_by username: params[:username]
    @project = Project.find_by user_id: @user.id, name: params[:project]
  end


  # Let's users upload new files to the project. The new files are
  # also commited to the backend git repository. They're added to the non_bare
  # repo, and pushed to the bare_repo.
  # FIXME - work on the push from non_bare to bare repo method.
  # FIXME - allow uploads of only supported images.

  def file_upload
    @project = Project.find params[:id]
    tmp = params[:file].tempfile
    file = File.join @project.satellitedir, params[:file].original_filename
    FileUtils.cp tmp.path, file
    if params[:file]
      image_commit @project, params[:file]
      flash[:notice] = "Your new image was added successfully! How sparkly!"
    else
      flash[:alert]  = "Your new image didn't get saved! How sad :("
    end
    redirect_to @project.urlbase
  end

  # Update files using this function. Updated files get commited to the non_bare repo
  # and then pushed to the bare repo.
  # FIXME - allow uploads of only supported images.
  def file_update
    @project = Project.find params[:id]
    tmp = params[:file].tempfile
    file = File.join @project.satellitedir, params[:image_name]
    FileUtils.cp tmp.path, file
    if params[:file]
        imagefile = params[:file]
        message = params[:message]
        satellite_commit @project.satelliterepo, params[:image_name], imagefile.read, message
        @project.pushtobare
        flash[:notice] = "#{params[:image_name]} has been updated! Shiny!"
    else
      flash[:alert] = "Unable to update #{params[:image_name]}. The server ponies are sad."
    end
    redirect_to @project.urlbase
  end

  # Delete files using this function.
  def file_delete
    @user = User.find_by username: params[:username]
    @project = Project.find_by user_id: @user.id, name: params[:project]
    file = File.join(@project.satellitedir, params[:image_name])
    FileUtils.rm(file) if File.exists?(file)
    satellite_delete(@project.satelliterepo,params[:image_name])
    @project.pushtobare
    flash[:notice] = "#{params[:image_name]} has been deleted!"
    redirect_to @project.urlbase
  end

  # WIP - Supposed to help in forking a repo that belongs to another user.
  # Fork works but creates only bare repos.

  def fork
    @user = User.find_by username: params[:username]
    @project = Project.find_by user_id: @user.id, name: params[:project]
    @forked_project = Project.new :name => @project.name,
                                  :parent => @project.id
    @forked_project.user_id = current_user.id

    if @project.private
      @forked_project.private = true
      @forked_project.uniqueurl = @project.uniqueurl
    end

    if @forked_project.save
      @forked_project_saved = true
      if @forked_project_saved

        git = Grit::Git.new @forked_project.path
        git.native(clone,{}, File.join(@project.path, '.git'),@forked_project.path)

        unless @forked_project.private

app/helpers/projects_helper.rb
module ProjectsHelper

  # pass in Glimage object
  def show_image(image)
    if image.is_svg?
      content_tag(:object, :data => "#{image.imagepath}") {}
    else
      tag :image, :src => "#{image.imagepath}"
    end
  end

  def private_check
    @user = User.find_by username: params[:username]
    @project = Project.find_by user_id: @user.id, name: params[:project]
    if user_signed_in?
      unless @project.private and ((params[:xid]!=@project.uniqueurl and current_user.id!=@project.user_id))
        true
      else false
      end
    else
      unless @project.private and (params[:xid]!=@project.uniqueurl)
        true
      else false
      end
    end
  end

  def owner_check
    @user = User.find_by username: params[:username]
    @project = Project.find_by user_id: @user.id, name: params[:project]
    if user_signed_in? and @project.user_id == current_user.id
      true
    else false
    end

  end
  
end

app/views/projects/_permissions_error.html.haml
Sorry, but you don't have permissions to access this page.

app/views/projects/commits.html.haml
- unless private_check
  = render 'permissions_error'
- else

  - content_for :title do
    = @project.name.titleize


  %article.project{ data: "log" }
    %header
      %h1.generated
        = avatar @project.user.email
        %p
          = link_to @user.username, "/#{@user.username}"
          = "/"
          %span 
            = link_to @project.name, "/#{@user.username}/#{@project.name}"
      %h2 
        - if @project.id == @project.parent
          %span.badge.author
            PARENT
        - else
          Forked from parent/project
          
    = render 'project_toolbar'
    = render 'shared/messages'

  
    - if @project.private and params[:xid] != @project.uniqueurl
      = link_to 'Unique link', @project.urlbase
  
    %section
      - unless @commits.empty?
        %div.feed
          - @commits.each do |commit|
            %div
              %header 
                = commit.author[:name]             
              %article
                %p
                  = link_to commit.message, File.join(@project.urlbase, 'commit', commit.tree_id)
              %footer
                %p
                  = distance_of_time_in_words_to_now Time.at(commit.epoch_time)
                  ago.
      - else
        %div
          - if user_signed_in?
            - unless current_user.id == @project.user.id
              .guide
                %p Work hasn't started on this project yet. Maybe you want to contribute?
                %form{action: "#"}
                  %input{type: "submit", value: "Fork this project!"}
            - else
              .guide
                %p Submit your design work on this project to start collaborating.
                %form{action: File.join(@project.urlbase, 'newfile')}
                  %input{type: "submit", value: "Add first file!"}
          - else
            .guide
              %p You'll need to sign in to work on these cool projects!
              %form{action: "/users/sign_in"}
                %input{type: "submit", value: "Sign in!"}

app/views/projects/create.html.haml
- content_for :title do
  Create New Project
#project_info
%pre
  = @project.inspect.to_yaml

app/views/projects/edit_svg.html.haml
- unless private_check and owner_check
  = render 'permissions_error'
- else

- unless private_check
  = render 'permissions_error'
- else

  - content_for :title do
    = @project.name.titleize

  %article.project
    %header
      %h1.generated
        = avatar @project.user.email
        %p
          = link_to @user.username, "/#{@user.username}"
          = "/"
          %span 
            = link_to @project.name, "/#{@user.username}/#{@project.name}"
      %h2 
        - if @project.id == @project.parent
          %span.badge.author
            PARENT
        - else
          Forked from parent/project

    = render 'project_toolbar'
    = render 'shared/messages'
  
    - if @project.private and params[:xid] != @project.uniqueurl
      = link_to 'Unique link', @project.urlbase
  
    %section
      %div
        = form_tag(:controller=>"projects", :action=>"update_svg", :id=>@project.id) do
          = sketchily_tag :sketch, :url => @path
          = label_tag "commit message"
          = text_field_tag "message", "Update #{@filename}"
          = hidden_field_tag 'filename', @filename
          = submit_tag

app/views/projects/file_history.html.haml
- unless private_check
  = render 'permissions_error'
- else

  - content_for :title do
    = @project.name.titleize
    File history

  - content_for :pagetitle do
    = link_to @project.name.titleize, @project.urlbase
    \/
    = link_to params[:image_name], File.join(@project.urlbase, 'master', params[:image_name])
    \/
    = "File history"

    = render 'project_toolbar'
    = render 'shared/messages'

  %br
  - @bloblist.each do |image, commit|
    = commit.author[:name]
    = commit.message
    = distance_of_time_in_words_to_now Time.at(commit.epoch_time)
    ago
    %br
    = data_image_tag(image,"100%",nil)

    %hr
    
  

app/views/projects/index.html.haml
%article.project
  %header
    %h1 Exciting Projects
    %h2 Stuff people are brewing, meant to inspire. 

  = render 'shared/messages'

  - unless @projects.empty?
    %section.album
      %div
        - @projects.each do |project|
          %div
            %p
              %img{ src: "/usercover.jpg"}
              = link_to project.name, project.urlbase
              %br
              Last updated #{distance_of_time_in_words_to_now project.updated_at} ago

  - else
    %section
      .guide
        %p Uh oh, looks like everyone's gotten lazy ;)
        %form{action: "/projects/new"}
          %input{type: "submit", value: "Be the first one to inspire!"}

app/views/projects/invite.html.haml
<?xml version="1.0" encoding="UTF-8" ?>

%sparkleshare
  %invite
    %address https://#{ENV['OPENSHIFT_APP_DNS'].downcase}/git
    %remote_path #{@git_dir}

app/views/projects/pull.html.haml
- unless private_check
  = render 'permissions_error'
- else

  - content_for :title do
    = 'Pull Request'

  - content_for :pagetitle do
    = link_to @project.name.titleize, @project.urlbase
    \/
    = link_to 'Pull Requests', File.join(@project.urlbase, 'pulls')
    \/
    = @pull.id

  = render 'project_toolbar'
  = render 'shared/messages'

  .center
    %h1
      = "##{@pull.id}"
    %ul
      %li
        = @pull.desc
      %li
        .meta
          = "First opened #{distance_of_time_in_words_to_now @pull.created_at} ago | "
          =  @pull.status
    %ul
      %li
        - if current_user.id == @project.user_id and @pull.status == 'open'
          = link_to 'Merge', File.join(@pull.id.to_s,'merge')
          |
          = link_to 'Close', File.join(@pull.id.to_s,'close')
        - if current_user.id == @project.user_id and @pull.status == 'closed'
          = link_to 'Re-open', File.join(@pull.id.to_s,'open')


  .comment_form
    = render partial: "comments/new", locals: {type: 'pull', id: @pull.id.to_s, ajax: @ajax, comment: @comment}
  %ul.comments
    = render partial: "comments/comment", collection: @comments
  - if !@comments.nil?
    = will_paginate @comments, :style => 'color:blue'

  

app/views/projects/pull_request.html.haml
- unless private_check and owner_check
  = render 'permissions_error'
- else
 
  - content_for :title do
    New Pull Request

  - content_for :pagetitle do
    = link_to @project.name.titleize, @project.urlbase
    \/
    = 'New Pull Request'

  = render 'project_toolbar'
  = render 'shared/messages'

  = form_tag handle_pull_request_project_path(@forked_project), multipart: true do
    = label_tag "description"
    = text_field_tag "description"
    = submit_tag 

app/views/projects/pulls.html.haml
- unless private_check
  = render 'permissions_error'
- else

  - content_for :title do
    = 'Pull Requests'

  - content_for :pagetitle do
    = link_to @project.name.titleize, @project.urlbase
    \/
    = 'Pull Requests'

  = render 'project_toolbar'
  %br


  .center
    - @pulls.each do |pull|
      %h1
        = link_to "##{pull.id}", File.join(@project.urlbase, 'pull',pull.id.to_s)
      %ul
        %li
          = pull.desc
        %li
          .meta
            = "First opened #{distance_of_time_in_words_to_now pull.created_at} ago | "
            =  pull.status
  

app/views/projects/settings.html.haml
- unless private_check
  = render 'permissions_error'
- else

  - content_for :title do
    = @project.name.titleize


  %article.project{ data: "settings" }
    %header
      %h1.generated
        = avatar @project.user.email
        %p
          = link_to @user.username, "/#{@user.username}"
          = "/"
          %span 
            = link_to @project.name, "/#{@user.username}/#{@project.name}"
      %h2 
        - if @project.id == @project.parent
          %span.badge.author
            PARENT
        - else
          Forked from parent/project

    = render 'project_toolbar'
    = render 'shared/messages'

    - if @project.private and params[:xid] != @project.uniqueurl
      %section
        %div
          %form{ action: @project.urlbase}
            %input{type: "submit", value: "Generate Unique Link"}

    %section
      %div
        %div.option
          -if user_signed_in? && @project.user_id == current_user.id
            = link_to "Delete project", project_path(@project.id), method: :delete, confirm: "Are you sure?"
        %aside
          %h1
            Project Settings
          %nav
            %ul
              %li.active
                %a{href: ""}Delete

app/views/projects/show.html.haml
- unless private_check
  = render 'permissions_error'
- else

  - content_for :title do
    = @project.name.titleize

  %article.project{ data: "current" }
    %header
      %h1.generated
        = avatar @project.user.email
        %p
          = link_to @user.username, "/#{@user.username}"
          = "/"
          %span
            = link_to @project.name, "/#{@user.username}/#{@project.name}"
      %h2
        - if @project.private == true
          %span.badge.type{:title => "Private Project"} PRV 
        -else
          %span.badge.type{:title => "Public Project"} PUB
        - if @project.id == @project.parent
          %span.badge.author PARENT
        - else FORK

        /= @project.desc
    = render 'project_toolbar'
    = render 'shared/messages'
    = render 'images'

    - if @project.private and params[:xid] != @project.uniqueurl
      %section
        %div
          %form{ action: @project.urlbase}
            %input{type: "submit", value: "Generate Unique Link"}


    %section.comments
      %section.showcomments
        = render partial: "comments/comment", collection: @comments.reverse
      %section.newcomment
        = render partial: "comments/new", locals: {type: 'project', id: @project.id.to_s, ajax: @ajax, comment: @comment}

app/views/projects/update.html.haml
- unless private_check
  = render 'permissions_error'
- else

  - content_for :title do
    = @project.name.titleize

  %article.project{ data: "update" }
    %header
      %h1.generated
        = avatar @project.user.email
        %p
          = link_to @user.username, "/#{@user.username}"
          = "/"
          %span 
            = link_to @project.name, "/#{@user.username}/#{@project.name}"
      %h2 
        - if @project.id == @project.parent
          %span.badge.author
            PARENT
        - else
          Forked from parent/project

    = render 'project_toolbar'
    = render 'shared/messages'

    %section
      %div
        = form_tag file_update_project_path(@project), multipart: true do
          = file_field_tag "file" 
          = text_field_tag "message","commit message"
          = hidden_field_tag "image_name", params[:image_name]
          = submit_tag 

app/views/projects/user_show.html.haml
- content_for :title do
  = @user.username.titleize


%article.project{ data: "projects"}
  %header
    %h1
      = avatar @user.email
      - unless @user == current_user
        #{@user.username}'s Projects
      - else
        My projects
    %h2
      = '@' + @user.username
      
  = render 'users/user_toolbar'
  = render 'shared/messages'
 

  - unless @projects.empty?
    %section.album
      %div
        - @projects.each do |project|
          %div
            %p
              %img{:src => "/usercover.jpg", :title => "Project Cover"}
              = link_to project.name, project.urlbase
              %br
              Last updated #{distance_of_time_in_words_to_now project.updated_at} ago
  - else
    %section
      .guide
        %p Create design projects on GlitterGallery to start collaborating with your circle.
        %form{action: "/projects/new"}
          %input{type: "submit", value: "Create first project!"}