config/routes.rb
Glitter::Application.routes.draw do

  devise_for :users,:controllers => { :registrations => 'registrations' }
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  match 'auth/:provider/callback' => "identities#create", :via => [:get,:post]
  match 'auth/failure' => "identities#failed_to_authenticate", :via => [:get,:post]
  

  resources :projects
  resources :identities, only: [:destroy,:index]
  resources :comments, only: [:new, :create, :destroy]
  resources :glitterposts
  resources :notifications, only: [:index,:show]

  
  post 'glitterposts/:id/edit' => 'glitterposts#update'
  get '/inspire' => 'projects#index'
  get '/dashboard' => 'dashboard#index', :as => :dashboard
  get '/:username/follow' => 'relationships#follow'
  get '/:username/unfollow' => 'relationships#unfollow'
  get '/:username' => 'users#show'
  get '/:username/projects' => 'projects#user_show'
  get '/:username/projects/following' => 'users#list_followed_projects', :as => :followed_projects
  get '/:username/:project' => 'projects#show'
  get '/:username/:project/commits' => 'projects#commits'
  get '/:username/:project/commit/:tree_id' => 'projects#projectcommit'
  get '/:username/:project/master/:image_name' => 'projects#masterbranch', :image_name => /[^\/]*/
  get '/:username/:project/master/:image_name/history' => 'projects#file_history', :image_name => /[^\/]*/
  get '/:username/:project/createsvg' => 'projects#new_svg'
  get '/:username/:project/newfile' => 'projects#newfile'
  get '/:username/:project/master/:image_name/edit' => 'projects#edit_svg', :image_name => /[^\/]*/
  get '/:username/:project/master/:image_name/update' => 'projects#update', :image_name => /[^\/]*/
  delete '/:username/:project/master/:image_name/delete' => 'projects#file_delete', :image_name => /[^\/]*/
  post '/:username/:project/follow' => 'projects#follow'
  get '/:username/:project/fork' => 'projects#fork'
  get '/:username/:project/forkyou' => 'projects#forkyou'
  get '/:username/:project/pull' => 'projects#pull_request'
  get '/:username/:project/pull/:pull_id' => 'projects#pull'
  get '/:username/:project/pull/:pull_id/merge' => 'projects#merge'
  get '/:username/:project/pull/:pull_id/close' => 'projects#close'
  get '/:username/:project/pull/:pull_id/open' => 'projects#open'
  get '/:username/:project/pulls' => 'projects#pulls'
  get '/:username/:project/settings' => 'projects#settings'
  get '/:username/:project/issues/new' => 'issues#new'
  get '/:username/:project/issues' => 'issues#index'
  post '/:username/:project/issues/new' => 'issues#create'
  get '/:username/:project/issue/:sub_id' => 'issues#show'
  post '/:username/:project/issue/:sub_id/close' => 'issues#close'

  get '/:username/:project/:xid' => 'projects#show'
  get '/:username/:project/:xid/commits' => 'projects#commits'
  get '/:username/:project/:xid/commit/:tree_id' => 'projects#projectcommit'
  get '/:username/:project/:xid/master/:image_name' => 'projects#masterbranch', :image_name => /[^\/]*/
  get '/:username/:project/:xid/master/:image_name/history' => 'projects#file_history', :image_name => /[^\/]*/
  get '/:username/:project/:xid/createsvg' => 'projects#new_svg'
  get '/:username/:project/:xid/newfile' => 'projects#newfile'
  get '/:username/:project/:xid/master/:image_name/edit' => 'projects#edit_svg', :image_name => /[^\/]*/
  get '/:username/:project/:xid/master/:image_name/update' => 'projects#update', :image_name => /[^\/]*/
  delete '/:username/:project/:xid/master/:image_name/delete' => 'projects#file_delete', :image_name => /[^\/]*/
  post '/:username/:project/:xid/follow' => 'projects#follow'
  get '/:username/:project/:xid/fork' => 'projects#fork'
  get '/:username/:project/:xid/forkyou' => 'projects#forkyou'
  get '/:username/:project/:xid/pull' => 'projects#pull_request'
  get '/:username/:project/:xid/pull/:pull_id' => 'projects#pull'
  get '/:username/:project/:xid/pull/:pull_id/merge' => 'projects#merge'
  get '/:username/:project/:xid/pull/:pull_id/close' => 'projects#close'
  get '/:username/:project/:xid/pull/:pull_id/open' => 'projects#open'
  get '/:username/:project/:xid/pulls' => 'projects#pulls'
  get '/:username/:project/:xid/settings' => 'projects#settings'
  get '/:username/:project/:xid/issues' => 'issues#index'
  get '/:username/:project/:xid/issue/:sub_id' => 'issues#show'
  get '/:username/:project/:xid/issues/new' => 'issues#new'
  post '/:username/:project/:xid/issues/new' => 'issues#create'
  post '/:username/:project/:xid/issue/:id/close' => 'issues#close'

  
  resources :projects do
    member do
      get 'projects/:id/invite.xml' => 'projects#invite'
      post :file_upload
      post :file_update
      post :handle_pull_request
      post :create_svg, :as => :create_svg
      post :edit_svg, :as => :edit_svg
      post :update_svg, :as => :update_svg
    end
  end 
end

app/models/glitterpost.rb
class Glitterpost < ActiveRecord::Base
  belongs_to :user

  validates :content, presence: true
  validates :title, presence: true
end

app/controllers/glitterposts_controller.rb
class GlitterpostsController < ApplicationController
  before_filter :store_return_to
  before_filter :authenticate_user!, except: [:show, :index]

  def new
  end

  def create
  	@glitterpost = Glitterpost.new(params[:glitterpost])
  	@glitterpost.user_id = current_user.id
  	if @glitterpost.save
  		redirect_to @glitterpost
  	else
      flash[:alert] = "Something went wrong, try glitterposting again."
  		render 'new'
  	end
  end

  def edit
    @glitterpost = Glitterpost.find(params[:id])
  end

  def update
    @glitterpost = Glitterpost.find(params[:id])
    if @glitterpost.update_attributes(params[:glitterpost])
      redirect_to @glitterpost
    else
      render 'edit'
    end
  end

  def index
  	@glitterposts = Glitterpost.all
  end
  

  def show
  	@glitterpost = Glitterpost.find(params[:id])
    @comments = Comment.where(polycomment_type: "glitterpost", polycomment_id: @glitterpost.id)
    @comments = pg @comments, 10
    @comment = Comment.new
    @ajax = params[:page].nil? || params[:page] == 1
    
  end

  def destroy
  	@glitterpost = Glitterpost.find(params[:id])
  	@glitterpost.destroy
  	redirect_to glitterposts_path
  end

end

app/views/glitterposts/edit.html.haml
- unless logged_in?
  = 'You need to login to be able to edit Glitterposts!'
  = link_to "Login now!", '/login'

- content_for :pagetitle do
  = "Editing Glitterpost"

= form_for :glitterpost do |f|
  - if @glitterpost.errors.any?
    %p
      #{pluralize(@glitterpost.errors.count, "error")} prohibited this post from being saved
    %ul
    = @glitterpost.errors.full_messages.each do |msg|
      %li
        = msg 

  = f.label "Title"
  = f.text_field :title
  = f.label "Emotions go here:"
  = f.text_area :content 
  = f.submit  
  
 

app/views/glitterposts/index.html.haml
- content_for :pagetitle do
  = "Recently added Glitterposts"

- @glitterposts.each do |post| 
  .meta
    = avatar(User.find(post.user_id).email)
    = link_to post.title, post
    %br
    Posted by
    = User.find(post.user_id).username
    on
    = time_tag post.created_at, :format => '%B %d, %Y'
    %hr

app/views/glitterposts/new.html.haml
- unless logged_in?
  = 'You need to login to be able to add Glitterposts!'
  = link_to "Login now!", '/login'

- content_for :pagetitle do
  = "New Glitterpost"

= form_for(:glitterpost, url: glitterposts_path) do |f|
  = f.label "Title"
  = f.text_field :title
  = f.label "Emotions go here:"
  = f.text_area :content 
  = f.submit  
  

app/views/glitterposts/show.html.haml
- markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
- content_for :title do
  = @glitterpost.title.titleize

- content_for :pagetitle do
  = @glitterpost.title.titleize

- content_for :toolbar do
  %ul
    %li
      = link_to 'Back', glitterposts_path
    - if logged_in? && (@glitterpost.user_id == current_user.id)
      %li  
        = link_to 'Edit', edit_glitterpost_path
      %li
        = link_to 'Destroy', glitterpost_path, method: :delete, data: { confirm: 'Are you sure?' }


.meta
  = avatar(User.find(@glitterpost.user_id).email)

  %p
    Posted by
    = User.find(@glitterpost.user_id).username
    on
    = time_tag @glitterpost.created_at, :format => '%B %d, %Y'

  %p
    Last updated
    = distance_of_time_in_words_to_now @glitterpost.updated_at
    ago

%hr
= raw markdown.render @glitterpost.content
    


.comment_form
  = render partial: "comments/new", locals: {type: 'glitterpost', id: @glitterpost.id.to_s, ajax: @ajax, comment: @comment}

%ul.comments
  = render partial: "comments/comment", collection: @comments
- if !@comments.nil?
  = will_paginate @comments, :style => 'color:blue'